### ISSUE TITLE
For upgrade and secret rotation scenario,  totally new set of secrets will bring outage and sometime unrecoverable.

### ISSUE THREAD

**Issue by Xiaohua-Shen** [SUSE/scf-secret-generator#23]
Given secret rotation as example:   same scf version,  update secret-generation-counter+1 to do the upgrade.   I call the old secret as `secret-1` and new secret as `secret-2`.

**Outage 1**:   after uaa upgrade successfully (finish uaa-upgrade and uaa-wait), cf upgrade is staring(make/upgrade).  
- all uaa pods are using `uaa.secret-2` 
- api-0 is `running` with `cf.secret-1` and api-1 is `ContainerCreating` with `cf.secret-2`.  

Now if someone try to `cf login`,  below error will be shown:
```
Server error, status code: 502, error code: 20004, message: The UAA service is currently unavailable
```

**analysis**:
The reason is api-0 use `cf.secret-1.uaa-ca-cert` to ssl with new uaa certificate `uaa.secret-2.uaa-server-cert`, they are not match. 
`cf.secret-1.uaa-ca-cert` = `uaa.secret-1.internal-ca-cert`, and can work with `uaa.secret-1.uaa-server-cert`

**some options may works**：
1.   keep internal-ca-cert/internal-ca-key unchanged during secret rotation/upgrade.  which means both cf and uaa namespace's new secret should have same internal-ca-cert/internal-ca-key as old secret.

2. scf-secret-generator command support input internal-ca-cert/internal-ca-key as parameter

3.  option 1 and 2 seems not rotate ca.  For rotate ca without outage, 
-- round 1: append new CA ( old CA + new CA)
-- round 2: upgrade deployment with new CA only

Another thing is : current generated certificate will be expired 30 years later,  that seems too long, should we reduce it to 1 year?

**Comment by Xiaohua-Shen** [comment]
Another worse scenario is same as above + concul replica 3,   the certificate mismatch may cause concul cluster not work.

```
  2018/05/10 07:24:05 [ERR] raft: Failed to make RequestVote RPC to {Voter 172.30.249.67:8300 172.30.249.67:8300}: x509: certificate signed by unknown authority (possibly because of “crypto/rsa: verification error” while trying to verify candidate authority certificate “SCF CA”)
   2018/05/10 07:24:07 [ERR] raft: Failed to make RequestVote RPC to {Voter 172.30.148.76:8300 172.30.148.76:8300}: x509: certificate signed by unknown authority (possibly because of “crypto/rsa: verification error” while trying to verify candidate authority certificate “SCF CA”)
   2018/05/10 07:24:07 [ERR] agent: failed to sync remote state: No cluster leader
```

which will cause   diego-api, diego-brain, diego-cell upgrade failed, always in `0/1 running` status. and  has error below:
```
Failed to connect to diego-api port 8889: Connection refused
```

**Comment by Xiaohua-Shen** [comment]
Now bcf is considering to do diego-cell sts upgrade  in canary mode (use position to control, upgrade part of diego cell pods first, then others).   And under secret rotation scenario,  beside certificate difference,  below password and secret difference(only list diego cell related) may cause some outage too . 

CONSUL_ENCRYPTION_KEYS:
MONIT_PASSWORD
 NATS_PASSWORD
UAA_CLIENTS_TCP_EMITTER_SECRET

**So**,  is it possible to keep PASSWORD/SECRET unchanged during upgrade?

**Comment by Xiaohua-Shen** [comment]
above issue is happen on a random development commit before SCF 2.8.0,   as https://github.com/SUSE/scf-secret-generator/issues/21#issuecomment-386758055 mentioned scf-secret-generator changed much.  so I will verify if same issue still existed in new release.

**Comment by jandubois** [comment]
> current generated certificate will be expired 30 years later, that seems too long, should we reduce it to 1 year?

We may want to keep the excessive expiration interval to avoid accidentally breaking a running install for a user. They can only un-brick such a system when an operator is around who can rotate secrets.

We believe it should be the responsibility of the operator to periodically rotate secrets. Breaking the running system, just as a reminder that they forgot to rotate seems a bit harsh.

We will add a Bosh property to the secrets generator to make this setting configurable though, so you will be able to set it to just one year, if you feel this is appropriate for your environment.

**Comment by jandubois** [comment]
> option 1 and 2 seems not rotate ca. For rotate ca without outage,
> -- round 1: append new CA ( old CA + new CA)
> -- round 2: upgrade deployment with new CA only

This sounds like a good idea. We have discussed this, and are not sure if it would totally eliminate the outage during secrets rotation: changing database passwords can still create a problem that can cascade into multi-pod failure. But keeping the certs valid can only make the outage shorter, so would still be a good thing.

We cannot commit to implementing this right now though. We will look at it again at a later point in time, but would be happy to discuss details with you if you feel that you need to tackle this more urgently and start implementing it yourself. 😄

**Comment by Xiaohua-Shen** [comment]
@jandubois sure, will discuss with you If I found some way to implement it.

Besides, for database passwords, I saw https://github.com/SUSE/scf/blob/436f3ba89fa381e85eff6a9ede0629437e2cfb2f/container-host-files/etc/scf/config/role-manifest.yml#L2169 and https://github.com/SUSE/scf/blob/436f3ba89fa381e85eff6a9ede0629437e2cfb2f/container-host-files/etc/scf/config/role-manifest.yml#L1771 set `immutable: true`, does that mean it's values will not be changed during upgrade/secret rotation?

**Comment by jandubois** [comment]
> does that mean it's values will not be changed during upgrade/secret rotation

Yes, that is exactly what the `immutable` setting does: their value is never changed once it has been generated: https://github.com/SUSE/scf-secret-generator/blob/master/secrets/secrets.go#L167-L181

We have been trying hard to reduce the number of immutable secrets, because they do represent a problem if they ever get compromised, but there are still some left. We need to find a way to be able to rotate all secrets.

**Comment by jandubois** [comment]
@Xiaohua-Shen I'm not sure what to do with this "Issue". Should we close it for now?

Cert expiration has been made configurable via https://github.com/SUSE/scf-secret-generator/pull/27

We have a story in our backlog/icebox about cert chaining during rotation, but no commitment if/when we would work on it.  Please let us know if you intend to work on it, so we don't duplicate effort.

So are there any other open action items? Maybe they can be filed as separate issues, and this one can be closed?
